[cmdcomp]
repository = "https://gitlab.com/uniquevision/utilities/cmdcomp"
version = "0.1.0"

[app]
name = "atmp"

[root.subcommands.welcome]

[root.subcommands.initialize]
alias = "init"
options = ["-", "aws"]

[root.subcommands.cd]
options = { type = "file", root_path = "$(dirname $(which atmp))/.." }

[root.subcommands.edit]
options = { type = "file", root_path = "$(dirname $(which atmp))/.." }

[root.subcommands.build]
[root.subcommands.start]
[root.subcommands.stop]

[root.subcommands.prepare]

[root.subcommands.self]
[root.subcommands.self.subcommands.format]
[root.subcommands.self.subcommands.lint]

[root.subcommands.help]

[root.subcommands.process]
alias = "ps"
options = ["-s"]

[root.subcommands.execute]
# 正しくはエイリアスではないが，補完内容が同じなので
alias = ["exec", "shell", "restart", "log", "url"]
options = { type = "command", execute = "atmp ps --services" }
